version: '2'

services:
  mc-debug:
    image: itzg/minecraft-server@sha256:8d5cbace1b377a26c089f31a14865fefc9f7b335a85b95f231af2b958186e2ec
    container_name: mc-debug
    ports:
      - 25565:25565
    volumes:
      - ./mc-debug:/data
    environment:
      - EULA=TRUE
      - ONLINE_MODE=FALSE
      - TYPE=PAPER
