version: '2'

services:
  mc-debug:
    image: itzg/minecraft-server@sha256:031f99a701917ebf2545fa68b35a43028fae49aac8c4ab6b9f64fb01553bd57c
    container_name: mc-debug
    ports:
      - 25565:25565
    volumes:
      - ./mc-debug:/data
    environment:
      - EULA=TRUE
      - ONLINE_MODE=FALSE
      - TYPE=PAPER
