version: '2'

services:
  mc-debug:
    image: itzg/minecraft-server@sha256:7174a6065cb27f905e8d8af354d0c075d3c98704e2972e690eb15ef7f401791d
    container_name: mc-debug
    ports:
      - 25565:25565
    volumes:
      - ./mc-debug:/data
    environment:
      - EULA=TRUE
      - ONLINE_MODE=FALSE
      - TYPE=PAPER
